function AppMeasurement_Module_AudienceManagement(d){var a=this;a.s=d;var b=window;b.s_c_in||(b.s_c_il=[],b.s_c_in=0);a._il=b.s_c_il;a._in=b.s_c_in;a._il[a._in]=a;b.s_c_in++;a._c="s_m";a.setup=function(c){b.DIL&&c&&(c.disableDefaultRequest=!0,c.disableScriptAttachment=!0,c.disableCORS=!0,c.secureDataCollection=!1,a.instance=b.DIL.create(c),a.tools=b.DIL.tools)};a.isReady=function(){return a.instance?!0:!1};a.getEventCallConfigParams=function(){return a.instance&&a.instance.api&&a.instance.api.getEventCallConfigParams?
a.instance.api.getEventCallConfigParams():{}};a.passData=function(b){a.instance&&a.instance.api&&a.instance.api.passData&&a.instance.api.passData(b)}}
"function"!==typeof window.DIL&&(window.DIL=function(e,f){var k=[],g,s;e!==Object(e)&&(e={});var t,m,F,O,A,y,K,G,P,Q,R,B,C,H,z;t=e.partner;m=e.containerNSID;F=!!e.disableDestinationPublishingIframe;O=e.iframeAkamaiHTTPS;A=e.mappings;y=e.uuidCookie;K=!0===e.enableErrorReporting;G=e.visitorService;P=e.declaredId;Q=!0===e.removeFinishedScriptsAndCallbacks;R=!0===e.delayAllUntilWindowLoad;B=!0===e.disableIDSyncs;C="undefined"===typeof e.secureDataCollection||!0===e.secureDataCollection;H=!0===e.useCORSOnly;
z="boolean"===typeof e.isCoopSafe?e.isCoopSafe:null;var S,T,L,I,U,V,W,X;S=!0===e.disableScriptAttachment;T=!0===e.disableDefaultRequest;L=e.afterResultForDefaultRequest;I=e.dpIframeSrc;U=!0===e.testCORS;V=!0===e.useJSONPOnly;W=e.visitorConstructor;X=!0===e.disableCORS;K&&DIL.errorModule.activate();var $=!0===window._dil_unit_tests;(g=f)&&k.push(g+"");if(!t||"string"!==typeof t)return g="DIL partner is invalid or not specified in initConfig",DIL.errorModule.handleError({name:"error",message:g,filename:"dil.js"}),
Error(g);g="DIL containerNSID is invalid or not specified in initConfig, setting to default of 0";if(m||"number"===typeof m)m=parseInt(m,10),!isNaN(m)&&0<=m&&(g="");g&&(m=0,k.push(g),g="");s=DIL.getDil(t,m);if(s instanceof DIL&&s.api.getPartner()===t&&s.api.getContainerNSID()===m)return s;if(this instanceof DIL)DIL.registerDil(this,t,m);else return new DIL(e,"DIL was not instantiated with the 'new' operator, returning a valid instance with partner = "+t+" and containerNSID = "+m);var u={IS_HTTPS:C||
"https:"===document.location.protocol,POST_MESSAGE_ENABLED:!!window.postMessage,COOKIE_MAX_EXPIRATION_DATE:"Tue, 19 Jan 2038 03:14:07 UTC",MILLIS_PER_DAY:864E5,DIL_COOKIE_NAME:"AAMC_"+encodeURIComponent(t)+"_"+m,FIRST_PARTY_SYNCS:"AMSYNCS",FIRST_PARTY_SYNCS_ON_PAGE:"AMSYNCSOP",HAS_JSON_STRINGIFY:window.JSON===Object(window.JSON)&&"function"===typeof window.JSON.stringify},M={stuffed:{}},p={},n={firingQueue:[],fired:[],firing:!1,sent:[],errored:[],reservedKeys:{sids:!0,pdata:!0,logdata:!0,callback:!0,
postCallbackFn:!0,useImageRequest:!0},callbackPrefix:"demdexRequestCallback",firstRequestHasFired:!1,useJSONP:!0,abortRequests:!1,num_of_jsonp_responses:0,num_of_jsonp_errors:0,num_of_cors_responses:0,num_of_cors_errors:0,corsErrorSources:[],num_of_img_responses:0,num_of_img_errors:0,toRemove:[],removed:[],readyToRemove:!1,platformParams:{d_nsid:m+"",d_rtbd:"json",d_jsonv:DIL.jsonVersion+"",d_dst:"1"},nonModStatsParams:{d_rtbd:!0,d_dst:!0,d_cts:!0,d_rs:!0},modStatsParams:null,adms:{TIME_TO_CATCH_ALL_REQUESTS_RELEASE:2E3,
calledBack:!1,mid:null,noVisitorAPI:!1,VisitorAPI:null,instance:null,releaseType:"no VisitorAPI",isOptedOut:!0,isOptedOutCallbackCalled:!1,admsProcessingStarted:!1,process:function(a){try{if(!this.admsProcessingStarted){this.admsProcessingStarted=!0;var b=this,c,d,l,h;if("function"===typeof a&&"function"===typeof a.getInstance){if(G===Object(G)&&(c=G.namespace)&&"string"===typeof c)d=a.getInstance(c,{idSyncContainerID:m});else{this.releaseType="no namespace";this.releaseRequests();return}if(d===Object(d)&&
d instanceof a&&"function"===typeof d.isAllowed&&"function"===typeof d.getMarketingCloudVisitorID&&"function"===typeof d.getCustomerIDs&&"function"===typeof d.isOptedOut){this.VisitorAPI=a;if(!d.isAllowed()){this.releaseType="VisitorAPI not allowed";this.releaseRequests();return}this.instance=d;l=function(a){"VisitorAPI"!==b.releaseType&&(b.mid=a,b.releaseType="VisitorAPI",b.releaseRequests())};h=d.getMarketingCloudVisitorID(l);if("string"===typeof h&&h.length){l(h);return}setTimeout(function(){"VisitorAPI"!==
b.releaseType&&(b.releaseType="timeout",b.releaseRequests())},this.getLoadTimeout());return}this.releaseType="invalid instance"}else this.noVisitorAPI=!0;this.releaseRequests()}}catch(e){this.releaseRequests()}},releaseRequests:function(){this.calledBack=!0;n.registerRequest()},getMarketingCloudVisitorID:function(){return this.instance?this.instance.getMarketingCloudVisitorID():null},getMIDQueryString:function(){var a=r.isPopulatedString,b=this.getMarketingCloudVisitorID();a(this.mid)&&this.mid===
b||(this.mid=b);return a(this.mid)?"d_mid="+this.mid+"&":""},getCustomerIDs:function(){return this.instance?this.instance.getCustomerIDs():null},getCustomerIDsQueryString:function(a){if(a===Object(a)){var b="",c=[],d=[],l,h;for(l in a)a.hasOwnProperty(l)&&(d[0]=l,h=a[l],h===Object(h)&&(d[1]=h.id||"",d[2]=h.authState||0,c.push(d),d=[]));if(d=c.length)for(a=0;a<d;a++)b+="&d_cid_ic="+q.encodeAndBuildRequest(c[a],"%01");return b}return""},getIsOptedOut:function(){this.instance?this.instance.isOptedOut([this,
this.isOptedOutCallback],this.VisitorAPI.OptOut.GLOBAL,!0):(this.isOptedOut=!1,this.isOptedOutCallbackCalled=!0)},isOptedOutCallback:function(a){this.isOptedOut=a;this.isOptedOutCallbackCalled=!0;n.registerRequest()},getLoadTimeout:function(){var a=this.instance;if(a){if("function"===typeof a.getLoadTimeout)return a.getLoadTimeout();if("undefined"!==typeof a.loadTimeout)return a.loadTimeout}return this.TIME_TO_CATCH_ALL_REQUESTS_RELEASE}},declaredId:{declaredId:{init:null,request:null},declaredIdCombos:{},
setDeclaredId:function(a,b){var c=r.isPopulatedString,d=encodeURIComponent;if(a===Object(a)&&c(b)){var l=a.dpid,h=a.dpuuid,e=null;if(c(l)&&c(h)){e=d(l)+"$"+d(h);if(!0===this.declaredIdCombos[e])return"setDeclaredId: combo exists for type '"+b+"'";this.declaredIdCombos[e]=!0;this.declaredId[b]={dpid:l,dpuuid:h};return"setDeclaredId: succeeded for type '"+b+"'"}}return"setDeclaredId: failed for type '"+b+"'"},getDeclaredIdQueryString:function(){var a=this.declaredId.request,b=this.declaredId.init,c=
encodeURIComponent,d="";null!==a?d="&d_dpid="+c(a.dpid)+"&d_dpuuid="+c(a.dpuuid):null!==b&&(d="&d_dpid="+c(b.dpid)+"&d_dpuuid="+c(b.dpuuid));return d}},registerRequest:function(a){var b=this.firingQueue;a===Object(a)&&b.push(a);this.firing||!b.length||R&&!DIL.windowLoaded||(this.adms.isOptedOutCallbackCalled||this.adms.getIsOptedOut(),this.adms.calledBack&&!this.adms.isOptedOut&&this.adms.isOptedOutCallbackCalled&&(this.adms.isOptedOutCallbackCalled=!1,a=b.shift(),a.src=a.src.replace(/demdex.net\/event\?d_nsid=/,
"demdex.net/event?"+this.adms.getMIDQueryString()+"d_nsid="),r.isPopulatedString(a.corsPostData)&&(a.corsPostData=a.corsPostData.replace(/^d_nsid=/,this.adms.getMIDQueryString()+"d_nsid=")),D.fireRequest(a),this.firstRequestHasFired||"script"!==a.tag&&"cors"!==a.tag||(this.firstRequestHasFired=!0)))},processVisitorAPI:function(){this.adms.process(W||window.Visitor)},requestRemoval:function(a){if(!Q)return"removeFinishedScriptsAndCallbacks is not boolean true";var b=this.toRemove,c,d;a===Object(a)&&
(c=a.script,d=a.callbackName,(c===Object(c)&&"SCRIPT"===c.nodeName||"no script created"===c)&&"string"===typeof d&&d.length&&b.push(a));if(this.readyToRemove&&b.length){d=b.shift();c=d.script;d=d.callbackName;"no script created"!==c?(a=c.src,c.parentNode.removeChild(c)):a=c;window[d]=null;try{delete window[d]}catch(l){}this.removed.push({scriptSrc:a,callbackName:d});DIL.variables.scriptsRemoved.push(a);DIL.variables.callbacksRemoved.push(d);return this.requestRemoval()}return"requestRemoval() processed"},
getCoopQueryString:function(){var a="";!0===z?a="&d_coop_safe=1":!1===z&&(a="&d_coop_unsafe=1");return a}};s=function(){var a="http://fast.",b="?d_nsid="+m+"#"+encodeURIComponent(document.location.href);if("string"===typeof I&&I.length)return I+b;u.IS_HTTPS&&(a=!0===O?"https://fast.":"https://");return a+t+".demdex.net/dest5.html"+b};var w={THROTTLE_START:3E4,MAX_SYNCS_LENGTH:649,throttleTimerSet:!1,id:"destination_publishing_iframe_"+t+"_"+m,url:s(),onPagePixels:[],iframeHost:null,getIframeHost:function(a){if("string"===
typeof a){var b=a.split("/");if(3<=b.length)return b[0]+"//"+b[2];k.push("getIframeHost: url is malformed: "+a);return a}},iframe:null,iframeHasLoaded:!1,sendingMessages:!1,messages:[],messagesPosted:[],messagesReceived:[],messageSendingInterval:u.POST_MESSAGE_ENABLED?null:100,ibsDeleted:[],jsonForComparison:[],jsonDuplicates:[],jsonWaiting:[],jsonProcessed:[],canSetThirdPartyCookies:!0,receivedThirdPartyCookiesNotification:!1,newIframeCreated:null,iframeIdChanged:!1,originalIframeHasLoadedAlready:null,
attachIframe:function(){function a(){d=document.createElement("iframe");d.sandbox="allow-scripts allow-same-origin";d.title="Adobe ID Syncing iFrame";d.id=c.id;d.style.cssText="display: none; width: 0; height: 0;";d.src=c.url;c.newIframeCreated=!0;b();document.body.appendChild(d)}function b(){q.addListener(d,"load",function(){d.className="aamIframeLoaded";c.iframeHasLoaded=!0;c.requestToProcess()})}var c=this,d=document.getElementById(this.id);d?"IFRAME"!==d.nodeName?(this.id+="_2",this.iframeIdChanged=
!0,a()):(this.newIframeCreated=!1,"aamIframeLoaded"!==d.className?(this.originalIframeHasLoadedAlready=!1,b()):(this.iframeHasLoaded=this.originalIframeHasLoadedAlready=!0,this.iframe=d,this.requestToProcess())):a();this.iframe=d},requestToProcess:function(a,b){function c(){d.jsonForComparison.push(a);d.jsonWaiting.push([a,b])}var d=this,l,h;l=n.adms.instance;a===Object(a)&&l===Object(l)&&l.idSyncContainerID===m&&(w.ibsDeleted.push(a.ibs),delete a.ibs);if(a&&!r.isEmptyObject(a))if(u.HAS_JSON_STRINGIFY)if(l=
JSON.stringify(a.ibs||[]),h=JSON.stringify(a.dests||[]),this.jsonForComparison.length){var e=!1,f,g,k;f=0;for(g=this.jsonForComparison.length;f<g;f++)if(k=this.jsonForComparison[f],l===JSON.stringify(k.ibs||[])&&h===JSON.stringify(k.dests||[])){e=!0;break}e?this.jsonDuplicates.push(a):c()}else c();else c();(this.receivedThirdPartyCookiesNotification||!u.POST_MESSAGE_ENABLED||this.iframeHasLoaded)&&this.jsonWaiting.length&&(l=this.jsonWaiting.shift(),!1===this.newIframeCreated&&delete l[0].ibs,this.process(l[0],
l[1]),this.requestToProcess());this.iframeHasLoaded&&this.messages.length&&!this.sendingMessages&&(this.throttleTimerSet||(this.throttleTimerSet=!0,setTimeout(function(){d.messageSendingInterval=u.POST_MESSAGE_ENABLED?null:150},this.THROTTLE_START)),this.sendingMessages=!0,this.sendMessages())},processSyncOnPage:function(a){var b,c,d;if((b=a.ibs)&&b instanceof Array&&(c=b.length))for(a=0;a<c;a++)d=b[a],d.syncOnPage&&this.checkFirstPartyCookie(d,"","syncOnPage")},process:function(a,b){var c=encodeURIComponent,
d,l,h,e,f,g;b===Object(b)&&(g=q.encodeAndBuildRequest(["",b.dpid||"",b.dpuuid||""],","));if((d=a.dests)&&d instanceof Array&&(l=d.length))for(h=0;h<l;h++)e=d[h],f=[c("dests"),c(e.id||""),c(e.y||""),c(e.c||"")],this.addMessage(f.join("|"));if((d=a.ibs)&&d instanceof Array&&(l=d.length))for(h=0;h<l;h++)e=d[h],f=[c("ibs"),c(e.id||""),c(e.tag||""),q.encodeAndBuildRequest(e.url||[],","),c(e.ttl||""),"",g,e.fireURLSync?"true":"false"],e.syncOnPage||(this.canSetThirdPartyCookies?this.addMessage(f.join("|")):
e.fireURLSync&&this.checkFirstPartyCookie(e,f.join("|")));this.jsonProcessed.push(a)},checkFirstPartyCookie:function(a,b,c){var d=(c="syncOnPage"===c?!0:!1)?u.FIRST_PARTY_SYNCS_ON_PAGE:u.FIRST_PARTY_SYNCS,l=this.getOnPageSyncData(d),h=!1,e=!1,f=Math.ceil((new Date).getTime()/u.MILLIS_PER_DAY);l?(l=l.split("*"),e=this.pruneSyncData(l,a.id,f),h=e.dataPresent,e=e.dataValid,h&&e||this.fireSync(c,a,b,l,d,f)):(l=[],this.fireSync(c,a,b,l,d,f))},getOnPageSyncData:function(a){var b=n.adms.instance;return b&&
"function"===typeof b.idSyncGetOnPageSyncInfo?b.idSyncGetOnPageSyncInfo():q.getDilCookieField(a)},pruneSyncData:function(a,b,c){var d=!1,l=!1,e,f,g;if(a instanceof Array)for(f=0;f<a.length;f++)e=a[f],g=parseInt(e.split("-")[1],10),e.match("^"+b+"-")?(d=!0,c<g?l=!0:(a.splice(f,1),f--)):c>=g&&(a.splice(f,1),f--);return{dataPresent:d,dataValid:l}},manageSyncsSize:function(a){if(a.join("*").length>this.MAX_SYNCS_LENGTH)for(a.sort(function(a,c){return parseInt(a.split("-")[1],10)-parseInt(c.split("-")[1],
10)});a.join("*").length>this.MAX_SYNCS_LENGTH;)a.shift()},fireSync:function(a,b,c,d,e,h){function f(a,b,d,c){return function(){g.onPagePixels[a]=null;var e=g.getOnPageSyncData(d),l=[];if(e){var e=e.split("*"),h,f,k;h=0;for(f=e.length;h<f;h++)k=e[h],k.match("^"+b.id+"-")||l.push(k)}g.setSyncTrackingData(l,b,d,c)}}var g=this;if(a){if("img"===b.tag){a=b.url;c=u.IS_HTTPS?"https:":"http:";var k,n,v;d=0;for(k=a.length;d<k;d++){n=a[d];v=/^\/\//.test(n);var x=new Image;q.addListener(x,"load",f(this.onPagePixels.length,
b,e,h));x.src=(v?c:"")+n;this.onPagePixels.push(x)}}}else this.addMessage(c),this.setSyncTrackingData(d,b,e,h)},addMessage:function(a){var b=encodeURIComponent,b=K?b("---destpub-debug---"):b("---destpub---");this.messages.push((u.POST_MESSAGE_ENABLED?"":b)+a)},setSyncTrackingData:function(a,b,c,d){a.push(b.id+"-"+(d+Math.ceil(b.ttl/60/24)));this.manageSyncsSize(a);q.setDilCookieField(c,a.join("*"))},sendMessages:function(){var a=this,b;this.messages.length?u.POST_MESSAGE_ENABLED?(b=encodeURIComponent("---destpub-combined---")+
this.messages.join("%01"),this.postMessage(b),this.messages=[],this.sendingMessages=!1):(b=this.messages.shift(),this.postMessage(b),setTimeout(function(){a.sendMessages()},this.messageSendingInterval)):this.sendingMessages=!1},postMessage:function(a){DIL.xd.postMessage(a,this.url,this.iframe.contentWindow);this.messagesPosted.push(a)},receiveMessage:function(a){var b=/^---destpub-to-parent---/;"string"===typeof a&&b.test(a)&&(b=a.replace(b,"").split("|"),"canSetThirdPartyCookies"===b[0]&&(this.canSetThirdPartyCookies=
"true"===b[1]?!0:!1,this.receivedThirdPartyCookiesNotification=!0,this.requestToProcess()),this.messagesReceived.push(a))}},N={traits:function(a){r.isValidPdata(a)&&(p.sids instanceof Array||(p.sids=[]),q.extendArray(p.sids,a));return this},pixels:function(a){r.isValidPdata(a)&&(p.pdata instanceof Array||(p.pdata=[]),q.extendArray(p.pdata,a));return this},logs:function(a){r.isValidLogdata(a)&&(p.logdata!==Object(p.logdata)&&(p.logdata={}),q.extendObject(p.logdata,a));return this},customQueryParams:function(a){r.isEmptyObject(a)||
q.extendObject(p,a,n.reservedKeys);return this},signals:function(a,b){var c,d=a;if(!r.isEmptyObject(d)){if(b&&"string"===typeof b)for(c in d={},a)a.hasOwnProperty(c)&&(d[b+c]=a[c]);q.extendObject(p,d,n.reservedKeys)}return this},declaredId:function(a){n.declaredId.setDeclaredId(a,"request");return this},result:function(a){"function"===typeof a&&(p.callback=a);return this},afterResult:function(a){"function"===typeof a&&(p.postCallbackFn=a);return this},useImageRequest:function(){p.useImageRequest=
!0;return this},clearData:function(){p={};return this},submit:function(){D.submitRequest(p);p={};return this},getPartner:function(){return t},getContainerNSID:function(){return m},getEventLog:function(){return k},getState:function(){var a={},b={};q.extendObject(a,n,{callbackPrefix:!0,useJSONP:!0,registerRequest:!0});q.extendObject(b,w,{attachIframe:!0,requestToProcess:!0,process:!0,sendMessages:!0});return{initConfig:e,pendingRequest:p,otherRequestInfo:a,destinationPublishingInfo:b}},idSync:function(a){if(B)return"Error: id syncs have been disabled";
if(a!==Object(a)||"string"!==typeof a.dpid||!a.dpid.length)return"Error: config or config.dpid is empty";if("string"!==typeof a.url||!a.url.length)return"Error: config.url is empty";var b=a.url,c=a.minutesToLive,d=encodeURIComponent,e=w,h,b=b.replace(/^https:/,"").replace(/^http:/,"");if("undefined"===typeof c)c=20160;else if(c=parseInt(c,10),isNaN(c)||0>=c)return"Error: config.minutesToLive needs to be a positive number";h=q.encodeAndBuildRequest(["",a.dpid,a.dpuuid||""],",");a=["ibs",d(a.dpid),
"img",d(b),c,"",h];e.addMessage(a.join("|"));n.firstRequestHasFired&&e.requestToProcess();return"Successfully queued"},aamIdSync:function(a){if(B)return"Error: id syncs have been disabled";if(a!==Object(a)||"string"!==typeof a.dpuuid||!a.dpuuid.length)return"Error: config or config.dpuuid is empty";a.url="//dpm.demdex.net/ibs:dpid="+a.dpid+"&dpuuid="+a.dpuuid;return this.idSync(a)},passData:function(a){if(r.isEmptyObject(a))return"Error: json is empty or not an object";w.ibsDeleted.push(a.ibs);delete a.ibs;
D.defaultCallback(a);return a},getPlatformParams:function(){return n.platformParams},getEventCallConfigParams:function(){var a=n,b=a.modStatsParams,c=a.platformParams,d;if(!b){b={};for(d in c)c.hasOwnProperty(d)&&!a.nonModStatsParams[d]&&(b[d.replace(/^d_/,"")]=c[d]);!0===z?b.coop_safe=1:!1===z&&(b.coop_unsafe=1);a.modStatsParams=b}return b},setAsCoopSafe:function(){z=!0;return this},setAsCoopUnsafe:function(){z=!1;return this}},D={corsMetadata:function(){var a="none",b=!0;"undefined"!==typeof XMLHttpRequest&&
XMLHttpRequest===Object(XMLHttpRequest)&&("withCredentials"in new XMLHttpRequest?a="XMLHttpRequest":(new Function("/*@cc_on return /^10/.test(@_jscript_version) @*/"))()?a="XMLHttpRequest":"undefined"!==typeof XDomainRequest&&XDomainRequest===Object(XDomainRequest)&&(b=!1),0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor")&&(b=!1));return{corsType:a,corsCookiesEnabled:b}}(),getCORSInstance:function(){return"none"===this.corsMetadata.corsType?null:new window[this.corsMetadata.corsType]},
submitRequest:function(a){n.registerRequest(D.createQueuedRequest(a));return!0},createQueuedRequest:function(a){var b=n,c,d=a.callback,e="img",h;if(!r.isEmptyObject(A)){var f,g,k;for(f in A)A.hasOwnProperty(f)&&(g=A[f],null!=g&&""!==g&&f in a&&!(g in a||g in n.reservedKeys)&&(k=a[f],null!=k&&""!==k&&(a[g]=k)))}r.isValidPdata(a.sids)||(a.sids=[]);r.isValidPdata(a.pdata)||(a.pdata=[]);r.isValidLogdata(a.logdata)||(a.logdata={});a.logdataArray=q.convertObjectToKeyValuePairs(a.logdata,"=",!0);a.logdataArray.push("_ts="+
(new Date).getTime());"function"!==typeof d&&(d=this.defaultCallback);b.useJSONP=!0!==a.useImageRequest;b.useJSONP&&(e="script",c=b.callbackPrefix+"_"+m+"_"+(new Date).getTime());b=this.makeRequestSrcData(a,c);V&&!H||!(h=this.getCORSInstance())||(e="cors");return{tag:e,src:b.src,corsSrc:b.corsSrc,internalCallbackName:c,callbackFn:d,postCallbackFn:a.postCallbackFn,useImageRequest:!!a.useImageRequest,requestData:a,corsInstance:h,corsPostData:b.corsPostData}},defaultCallback:function(a,b){w.processSyncOnPage(a);
var c,d,e,h,f,g,k,m,v;if((c=a.stuff)&&c instanceof Array&&(d=c.length))for(e=0;e<d;e++)if((h=c[e])&&h===Object(h)){f=h.cn;g=h.cv;k=h.ttl;if("undefined"===typeof k||""===k)k=Math.floor(q.getMaxCookieExpiresInMinutes()/60/24);m=h.dmn||"."+document.domain.replace(/^www\./,"");v=h.type;f&&(g||"number"===typeof g)&&("var"!==v&&(k=parseInt(k,10))&&!isNaN(k)&&q.setCookie(f,g,1440*k,"/",m,!1),M.stuffed[f]=g)}c=a.uuid;r.isPopulatedString(c)&&!r.isEmptyObject(y)&&(d=y.path,"string"===typeof d&&d.length||(d=
"/"),e=parseInt(y.days,10),isNaN(e)&&(e=100),q.setCookie(y.name||"aam_did",c,1440*e,d,y.domain||"."+document.domain.replace(/^www\./,""),!0===y.secure));F||n.abortRequests||w.requestToProcess(a,b)},makeRequestSrcData:function(a,b){a.sids=r.removeEmptyArrayValues(a.sids||[]);a.pdata=r.removeEmptyArrayValues(a.pdata||[]);var c=n,d=c.platformParams,e=q.encodeAndBuildRequest(a.sids,","),h=q.encodeAndBuildRequest(a.pdata,","),f=(a.logdataArray||[]).join("&");delete a.logdataArray;var g=u.IS_HTTPS?"https://":
"http://",k=c.declaredId.getDeclaredIdQueryString(),p=c.adms.instance?c.adms.getCustomerIDsQueryString(c.adms.getCustomerIDs()):"",v;v=[];var x,E,s,Y;for(x in a)if(!(x in c.reservedKeys)&&a.hasOwnProperty(x))if(E=a[x],x=encodeURIComponent(x),E instanceof Array)for(s=0,Y=E.length;s<Y;s++)v.push(x+"="+encodeURIComponent(E[s]));else v.push(x+"="+encodeURIComponent(E));v=v.length?"&"+v.join("&"):"";e="d_nsid="+d.d_nsid+c.getCoopQueryString()+k+p+(e.length?"&d_sid="+e:"")+(h.length?"&d_px="+h:"")+(f.length?
"&d_ld="+encodeURIComponent(f):"");d="&d_rtbd="+d.d_rtbd+"&d_jsonv="+d.d_jsonv+"&d_dst="+d.d_dst;g=g+t+".demdex.net/event";h=c=g+"?"+e+(c.useJSONP?d+"&d_cb="+(b||""):"")+v;2048<c.length&&(c=c.substring(0,2048).substring(0,c.lastIndexOf("&")));return{corsSrc:g+"?"+(U?"testcors=1&d_nsid="+m+"&":"")+"_ts="+(new Date).getTime(),src:c,originalSrc:h,corsPostData:e+d+v,isDeclaredIdCall:""!==k}},fireRequest:function(a){if("img"===a.tag)this.fireImage(a);else{var b=n.declaredId,b=b.declaredId.request||b.declaredId.init||
{},b={dpid:b.dpid||"",dpuuid:b.dpuuid||""};"script"===a.tag?this.fireScript(a,b):"cors"===a.tag&&this.fireCORS(a,b)}},fireImage:function(a){var b=n,c,d;b.abortRequests||(b.firing=!0,c=new Image(0,0),b.sent.push(a),c.onload=function(){b.firing=!1;b.fired.push(a);b.num_of_img_responses++;b.registerRequest()},d=function(d){g="imgAbortOrErrorHandler received the event of type "+d.type;k.push(g);b.abortRequests=!0;b.firing=!1;b.errored.push(a);b.num_of_img_errors++;b.registerRequest()},c.addEventListener?
(c.addEventListener("error",d,!1),c.addEventListener("abort",d,!1)):c.attachEvent&&(c.attachEvent("onerror",d),c.attachEvent("onabort",d)),c.src=a.src)},fireScript:function(a,b){var c=this,d=n,e,h,f=a.src,m=a.postCallbackFn,q="function"===typeof m,p=a.internalCallbackName;d.abortRequests||(d.firing=!0,window[p]=function(c){try{c!==Object(c)&&(c={});B&&(w.ibsDeleted.push(c.ibs),delete c.ibs);var e=a.callbackFn;d.firing=!1;d.fired.push(a);d.num_of_jsonp_responses++;e(c,b);q&&m(c,b)}catch(f){f.message=
"DIL jsonp callback caught error with message "+f.message;g=f.message;k.push(g);f.filename=f.filename||"dil.js";f.partner=t;DIL.errorModule.handleError(f);try{e({error:f.name+"|"+f.message},b),q&&m({error:f.name+"|"+f.message},b)}catch(l){}}finally{d.requestRemoval({script:h,callbackName:p}),d.registerRequest()}},S||H?(d.firing=!1,d.requestRemoval({script:"no script created",callbackName:p})):(h=document.createElement("script"),h.addEventListener&&h.addEventListener("error",function(b){d.requestRemoval({script:h,
callbackName:p});g="jsonp script tag error listener received the event of type "+b.type+" with src "+f;c.handleScriptError(g,a)},!1),h.type="text/javascript",h.src=f,e=DIL.variables.scriptNodeList[0],e.parentNode.insertBefore(h,e)),d.sent.push(a),d.declaredId.declaredId.request=null)},fireCORS:function(a,b){var c=this,d=n,e=this.corsMetadata.corsType,f=a.corsSrc,m=a.corsInstance,q=a.corsPostData,p=a.postCallbackFn,s="function"===typeof p;if(!d.abortRequests&&!X){d.firing=!0;try{m.open("post",f,!0),
"XMLHttpRequest"===e&&(m.withCredentials=!0,m.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),m.onreadystatechange=function(){if(4===this.readyState&&200===this.status)a:{var e;try{if(e=JSON.parse(this.responseText),e!==Object(e)){c.handleCORSError(a,b,"Response is not JSON");break a}}catch(f){c.handleCORSError(a,b,"Error parsing response as JSON");break a}B&&(w.ibsDeleted.push(e.ibs),delete e.ibs);try{var h=a.callbackFn;d.firing=!1;d.fired.push(a);d.num_of_cors_responses++;h(e,
b);s&&p(e,b)}catch(l){l.message="DIL handleCORSResponse caught error with message "+l.message;g=l.message;k.push(g);l.filename=l.filename||"dil.js";l.partner=t;DIL.errorModule.handleError(l);try{h({error:l.name+"|"+l.message},b),s&&p({error:l.name+"|"+l.message},b)}catch(m){}}finally{d.registerRequest()}}}),m.onerror=function(){c.handleCORSError(a,b,"onerror")},m.ontimeout=function(){c.handleCORSError(a,b,"ontimeout")},m.send(q)}catch(r){this.handleCORSError(a,b,"try-catch")}d.sent.push(a);d.declaredId.declaredId.request=
null}},handleCORSError:function(a,b,c){n.num_of_cors_errors++;n.corsErrorSources.push(c);"ontimeout"===c||H||(a.tag="script",this.fireScript(a,b))},handleScriptError:function(a,b){n.num_of_jsonp_errors++;this.handleRequestError(a,b)},handleRequestError:function(a,b){var c=n;k.push(a);c.abortRequests=!0;c.firing=!1;c.errored.push(b);c.registerRequest()}},r={isValidPdata:function(a){return a instanceof Array&&this.removeEmptyArrayValues(a).length?!0:!1},isValidLogdata:function(a){return!this.isEmptyObject(a)},
isEmptyObject:function(a){if(a!==Object(a))return!0;for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},removeEmptyArrayValues:function(a){for(var b=0,c=a.length,d,e=[],b=0;b<c;b++)d=a[b],"undefined"!==typeof d&&null!==d&&""!==d&&e.push(d);return e},isPopulatedString:function(a){return"string"===typeof a&&a.length}},q={addListener:function(){if(document.addEventListener)return function(a,b,c){a.addEventListener(b,function(a){"function"===typeof c&&c(a)},!1)};if(document.attachEvent)return function(a,
b,c){a.attachEvent("on"+b,function(a){"function"===typeof c&&c(a)})}}(),convertObjectToKeyValuePairs:function(a,b,c){var d=[],e,f;b||(b="=");for(e in a)a.hasOwnProperty(e)&&(f=a[e],"undefined"!==typeof f&&null!==f&&""!==f&&d.push(e+b+(c?encodeURIComponent(f):f)));return d},encodeAndBuildRequest:function(a,b){return this.map(a,function(a){return encodeURIComponent(a)}).join(b)},map:function(a,b){if(Array.prototype.map)return a.map(b);if(void 0===a||null===a)throw new TypeError;var c=Object(a),d=c.length>>>
0;if("function"!==typeof b)throw new TypeError;for(var e=Array(d),f=0;f<d;f++)f in c&&(e[f]=b.call(b,c[f],f,c));return e},filter:function(a,b){if(!Array.prototype.filter){if(void 0===a||null===a)throw new TypeError;var c=Object(a),d=c.length>>>0;if("function"!==typeof b)throw new TypeError;for(var e=[],f=0;f<d;f++)if(f in c){var g=c[f];b.call(b,g,f,c)&&e.push(g)}return e}return a.filter(b)},getCookie:function(a){a+="=";var b=document.cookie.split(";"),c,d,e;c=0;for(d=b.length;c<d;c++){for(e=b[c];" "===
e.charAt(0);)e=e.substring(1,e.length);if(0===e.indexOf(a))return decodeURIComponent(e.substring(a.length,e.length))}return null},setCookie:function(a,b,c,d,e,f){var g=new Date;c&&(c*=6E4);document.cookie=a+"="+encodeURIComponent(b)+(c?";expires="+(new Date(g.getTime()+c)).toUTCString():"")+(d?";path="+d:"")+(e?";domain="+e:"")+(f?";secure":"")},extendArray:function(a,b){return a instanceof Array&&b instanceof Array?(Array.prototype.push.apply(a,b),!0):!1},extendObject:function(a,b,c){var d;if(a===
Object(a)&&b===Object(b)){for(d in b)!b.hasOwnProperty(d)||!r.isEmptyObject(c)&&d in c||(a[d]=b[d]);return!0}return!1},getMaxCookieExpiresInMinutes:function(){return((new Date(u.COOKIE_MAX_EXPIRATION_DATE)).getTime()-(new Date).getTime())/1E3/60},getCookieField:function(a,b){var c=this.getCookie(a),d=decodeURIComponent;if("string"===typeof c){var c=c.split("|"),e,f;e=0;for(f=c.length-1;e<f;e++)if(d(c[e])===b)return d(c[e+1])}return null},getDilCookieField:function(a){return this.getCookieField(u.DIL_COOKIE_NAME,
a)},setCookieField:function(a,b,c){var d=this.getCookie(a),e=!1,f=encodeURIComponent;b=f(b);c=f(c);if("string"===typeof d){var d=d.split("|"),g,f=0;for(g=d.length-1;f<g;f++)if(d[f]===b){d[f+1]=c;e=!0;break}e||(f=d.length,d[f]=b,d[f+1]=c)}else d=[b,c];this.setCookie(a,d.join("|"),this.getMaxCookieExpiresInMinutes(),"/",this.getDomain(),!1)},setDilCookieField:function(a,b){return this.setCookieField(u.DIL_COOKIE_NAME,a,b)},getDomain:function(a){!a&&window.location&&(a=window.location.hostname);if(a)if(/^[0-9.]+$/.test(a))a=
"";else{var b=a.split("."),c=b.length-1,d=c-1;1<c&&2>=b[c].length&&(2===b[c-1].length||0>",DOMAIN_2_CHAR_EXCEPTIONS,".indexOf(","+b[c]+","))&&d--;if(0<d)for(a="";c>=d;)a=b[c]+(a?".":"")+a,c--}return a}};"error"===t&&0===m&&q.addListener(window,"load",function(){DIL.windowLoaded=!0});var Z=!1,J=function(){Z||(Z=!0,n.registerRequest(),aa(),F||n.abortRequests||w.attachIframe(),n.readyToRemove=!0,n.requestRemoval())},aa=function(){F||setTimeout(function(){T||n.firstRequestHasFired||("function"===typeof L?
N.afterResult(L).submit():N.submit())},DIL.constants.TIME_TO_DEFAULT_REQUEST)};C=document;"error"!==t&&(DIL.windowLoaded?J():"complete"!==C.readyState&&"loaded"!==C.readyState?q.addListener(window,"load",function(){DIL.windowLoaded=!0;J()}):(DIL.windowLoaded=!0,J()));if("error"!==t)try{DIL.xd.receiveMessage(function(a){w.receiveMessage(a.data)},w.getIframeHost(w.url))}catch(ba){}n.declaredId.setDeclaredId(P,"init");n.processVisitorAPI();this.api=N;this.getStuffedVariable=function(a){var b=M.stuffed[a];
b||"number"===typeof b||(b=q.getCookie(a))||"number"===typeof b||(b="");return b};this.validators=r;this.helpers=q;this.constants=u;this.log=k;$&&(this.pendingRequest=p,this.requestController=n,this.setDestinationPublishingUrl=s,this.destinationPublishing=w,this.requestProcs=D,this.variables=M,this.callWindowLoadFunctions=J)},function(){var e=document,f;null==e.readyState&&e.addEventListener&&(e.readyState="loading",e.addEventListener("DOMContentLoaded",f=function(){e.removeEventListener("DOMContentLoaded",
f,!1);e.readyState="complete"},!1))}(),DIL.extendStaticPropertiesAndMethods=function(e){var f;if(e===Object(e))for(f in e)e.hasOwnProperty(f)&&(this[f]=e[f])},DIL.extendStaticPropertiesAndMethods({version:"6.11",jsonVersion:1,constants:{TIME_TO_DEFAULT_REQUEST:50},variables:{scriptNodeList:document.getElementsByTagName("script"),scriptsRemoved:[],callbacksRemoved:[]},windowLoaded:!1,dils:{},isAddedPostWindowLoad:function(e){this.windowLoaded="function"===typeof e?!!e():"boolean"===typeof e?e:!0},
create:function(e){try{return new DIL(e)}catch(f){throw Error("Error in attempt to create DIL instance with DIL.create(): "+f.message);}},registerDil:function(e,f,k){f=f+"$"+k;f in this.dils||(this.dils[f]=e)},getDil:function(e,f){var k;"string"!==typeof e&&(e="");f||(f=0);k=e+"$"+f;return k in this.dils?this.dils[k]:Error("The DIL instance with partner = "+e+" and containerNSID = "+f+" was not found")},dexGetQSVars:function(e,f,k){f=this.getDil(f,k);return f instanceof this?f.getStuffedVariable(e):
""},xd:{postMessage:function(e,f,k){var g=1;f&&(window.postMessage?k.postMessage(e,f.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):f&&(k.location=f.replace(/#.*$/,"")+"#"+ +new Date+g++ +"&"+e))},receiveMessage:function(e,f){var k;try{if(window.postMessage)if(e&&(k=function(g){if("string"===typeof f&&g.origin!==f||"[object Function]"===Object.prototype.toString.call(f)&&!1===f(g.origin))return!1;e(g)}),window.addEventListener)window[e?"addEventListener":"removeEventListener"]("message",k,!1);else window[e?
"attachEvent":"detachEvent"]("onmessage",k)}catch(g){}}}}),DIL.errorModule=function(){var e=DIL.create({partner:"error",containerNSID:0,disableDestinationPublishingIframe:!0}),f={harvestererror:14138,destpuberror:14139,dpmerror:14140,generalerror:14137,error:14137,noerrortypedefined:15021,evalerror:15016,rangeerror:15017,referenceerror:15018,typeerror:15019,urierror:15020},k=!1;return{activate:function(){k=!0},handleError:function(g){if(!k)return"DIL error module has not been activated";g!==Object(g)&&
(g={});var s=g.name?(g.name+"").toLowerCase():"",t=[];g={name:s,filename:g.filename?g.filename+"":"",partner:g.partner?g.partner+"":"no_partner",site:g.site?g.site+"":document.location.href,message:g.message?g.message+"":""};t.push(s in f?f[s]:f.noerrortypedefined);e.api.pixels(t).logs(g).useImageRequest().submit();return"DIL error report sent"},pixelMap:f}}(),DIL.tools={},DIL.modules={helpers:{handleModuleError:function(e,f,k){var g="";f=f||"Error caught in DIL module/submodule: ";e===Object(e)?
g=f+(e.message||"err has no message"):(g=f+"err is not a valid object",e={});e.message=g;k instanceof DIL&&(e.partner=k.api.getPartner());DIL.errorModule.handleError(e);return this.errorMessage=g}}});
